### ISSUE TITLE
Possible Regression

### ISSUE THREAD

**Issue by mmk0083** [vue-leaflet/vue-leaflet#231]
When unmounting a component with a `Map` we noticed the following error in the browser console:

```
leaflet-src.esm.5b8a8dab.js:4 Uncaught TypeError: Cannot read properties of undefined (reading '_leaflet_pos')
    at lt (leaflet-src.esm.5b8a8dab.js:4:21106)
    at Proxy._getMapPanePos (leaflet-src.esm.5b8a8dab.js:4:43041)
    at Proxy._moved (leaflet-src.esm.5b8a8dab.js:4:43101)
    at Proxy.getCenter (leaflet-src.esm.5b8a8dab.js:4:35068)
    at Proxy.moveEndHandler (UserLocations.0309a204.js:1:8091)
    at UserLocations.0309a204.js:1:499
```

From what we can tell - this is being caused when one of our watchers is calling `leafletObject.setView()` right before the unmount takes place. It looks like a [very similar bug](https://github.com/vue-leaflet/Vue2Leaflet/issues/613) was found and [fixed](https://github.com/vue-leaflet/Vue2Leaflet/pull/638/files) in the Vue2Leaflet code by cancelling debounced calls.

The map code [does seem to debounce](https://github.com/vue-leaflet/vue-leaflet/blob/master/src/components/LMap.vue#L385) the `moveend` event but I do not see a cancel for this debounce.

**Comment by tony-engineering** [comment]
I can reproduce this bug with Leafleet 1.9.3 with NextJS https://www.npmjs.com/package/leaflet.
I navigate to my app, then very quickly press ALT + LEFT ARROW, then ALT + RIGHT ARROW to go to previous page and return to the current page. When I navigate slowly (I wait 0.5 seconds between left arrow and right arrow), then the problem doesn't appear. See video.

https://user-images.githubusercontent.com/9582205/212672943-1222ac95-1f09-457c-a0d4-b46deab33d71.mp4

When I click on error message, it show me the triggered place `return t._leaflet_pos` .

I noticed that because my automated testing framework (Cypress) is navigating very quickly.

**Comment by mikeu** [comment]
Thank you for reporting this @mmk0083 , and continuing to investigate it @tony-engineering ! I've just released [v0.8.0](https://github.com/vue-leaflet/vue-leaflet/releases/tag/v0.8.0), which should do a better job of removing listeners on unmount. Please try it out, and let me know if you're still able the trigger the error.

**Comment by mmk0083** [comment]
@mikeu Thanks for looking into this. Unfortunately the error still happens for me.
